name: Test Version

on: 
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

jobs:
  version:
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    secrets: inherit
    with:
      increment: false
      build-var: IOS_BUILD_NUMBER

  test_version:
    name: Test Version
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - name: Display version
        run: |
          echo "Year: ${{ needs.version.outputs.year }}"
          echo "Release: ${{ needs.version.outputs.release }}"
          echo "Build: ${{ needs.version.outputs.build }}"
          echo "Version: ${{ needs.version.outputs.version }}"
          echo "Time: ${{ needs.version.outputs.time }}"
          echo "Short SHA: ${{ needs.version.outputs.commit-sha }}"
          echo "Url: ${{ needs.version.outputs.commit-url }}"