name: Test Version

on: 
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

jobs:
  version:
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    secrets: inherit
    with:
      increment: ${{ inputs.increment == 'true' }}

  build_number:
    uses: starburst997/yearly-version/.github/workflows/build.yml@v1
    secrets: inherit
    with:
      name: IOS_BUILD_NUMBER

  test_version:
    name: Test Version
    runs-on: ubuntu-latest
    needs: [version, build_number]
    steps:
      - name: Display version
        run: |
          echo "Year: ${{ needs.version.outputs.year }}"
          echo "Release: ${{ needs.version.outputs.release }}"
          echo "Version: ${{ needs.version.outputs.version }}"
          echo "Build: ${{ needs.build_number.outputs.build_number }}"