name: Get Version

on: 
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        required: false
        default: 'false'
        options:
          - true
          - false
      build-var:
        type: string
        required: false
        default: ''

  workflow_call:
    outputs:
      year:
        value: ${{ jobs.version.outputs.year }}
      release:
        value: ${{ jobs.version.outputs.release }}
      build:
        value: ${{ jobs.version.outputs.build }}
      version:
        value: ${{ jobs.version.outputs.version }}
      time:
        value: ${{ jobs.version.outputs.time }}
      commit-sha:
        value: ${{ jobs.version.outputs.commit-sha }}
      commit-url:
        value: ${{ jobs.version.outputs.commit-url }}
    inputs:
      increment:
        required: false
        type: boolean
      build-var:
        required: false
        type: string

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      year: ${{ steps.year.outputs.year }}
      release: ${{ steps.release.outputs.release }}
      build: ${{ steps.build.outputs.build }}
      version: ${{ steps.version.outputs.version }}
      time: ${{ steps.time.outputs.time }}
      commit-sha: ${{ steps.extra.outputs.sha }}
      commit-url: ${{ steps.extra.outputs.url }}
    steps:
      - name: Save timestamp
        id: time
        run: |
          printf 'TIME=%(%s)T\n' >> "$GITHUB_ENV"
          printf 'time=%(%s)T\n' >> "$GITHUB_OUTPUT"
      - run: echo Time is $TIME

      - name: Set YEAR
        id: year
        run: |
          echo "YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "year=$(date +%Y)" >> $GITHUB_OUTPUT
      - run: echo Year is $YEAR
      
      - name: Set RELEASE
        id: release
        env:
          RELEASE_NUMBER: ${{ vars.RELEASE_NUMBER }}
          INCREMENT: ${{ inputs.increment == true || inputs.increment == 'true' }}
        run: |
          [[ $INCREMENT == true ]] && echo "RELEASE=$(($RELEASE_NUMBER+2))" >> $GITHUB_ENV
          [[ $INCREMENT == true ]] && echo "release=$(($RELEASE_NUMBER+2))" >> $GITHUB_OUTPUT
          [[ $INCREMENT != true ]] && echo "RELEASE=$(($RELEASE_NUMBER+1))" >> $GITHUB_ENV
          [[ $INCREMENT != true ]] && echo "release=$(($RELEASE_NUMBER+1))" >> $GITHUB_OUTPUT
          echo "Finished!"
      - run: echo Release is $RELEASE
      
      - name: Increment BUILD_NUMBER locally
        id: build
        env:
          BUILD_NUMBER: ${{ vars[inputs.build-var] }}
        run: |
          echo "build=$(($BUILD_NUMBER+1))" >> $GITHUB_OUTPUT
          echo "BUILD_NUMBER_VERSION=.$(($BUILD_NUMBER+1))" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$(($BUILD_NUMBER+1))" >> $GITHUB_ENV
      - run: echo "BUILD_NUMBER is $BUILD_NUMBER"

      - name: Set empty BUILD_NUMBER_VERSION
        if: ${{ inputs.build-var == '' }}
        run: |
          echo "BUILD_NUMBER_VERSION=" >> $GITHUB_ENV

      - name: Set VERSION
        id: version
        run: |
          echo "VERSION=$YEAR.$RELEASE$BUILD_NUMBER_VERSION" >> $GITHUB_ENV
          echo "version=$YEAR.$RELEASE$BUILD_NUMBER_VERSION" >> $GITHUB_OUTPUT
      - run: echo Version is $VERSION

      - name: Increment Version
        uses: starburst997/increment@v2
        if: ${{ inputs.increment == true || inputs.increment == 'true' }}
        with:
          name: 'RELEASE_NUMBER'
          amount: 1
          token: ${{ secrets.GH_PAT }}

      - name: Increment Build Number
        uses: starburst997/increment@v2
        if: ${{ inputs.build-var != '' }}
        with:
          name: ${{ inputs.build-var }}
          amount: 1
          token: ${{ secrets.GH_PAT }}

      - name: Some extra vars
        id: extra
        run: |
          echo "sha=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
          echo "url=${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_OUTPUT
      - run: |
          echo SHA is ${{ steps.extra.outputs.sha }}
          echo URL is ${{ steps.extra.outputs.url }}